apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 80
  selector:
    app: guestbook
    tier: frontend
  externalIPs:
    - 35.188.213.59
